### PR TITLE
add private download strategy

### PR DESCRIPTION
**Pull request by T-Kukawka**
Fix going together with: https://github.com/giantswarm/opsctl/pull/338/files

Homebrew removed strategies: https://github.com/Homebrew/brew/pull/5112/files

Tested locally.

### CODE REVIEW

**Comment by marians** [comment]
Thanks a bunch for taking this!

FYI this fixes https://github.com/giantswarm/giantswarm/issues/5289

**Review by marians — APPROVED** [review]
Didn't test. I fit works for you, it should work for us :)

**Review by calvix — APPROVED** [review]
Ruby! oh yay!

**Comment by marians** [comment]
@T-Kukawka Please don't forget to merge this

**Pull request merged**
